name: Deploy to Firebase Hosting on PR
"on": pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Create Env File"
        run: |
          touch .env
          echo "${{ secrets.REACT_APP_ENV_FILE }}" > .env
        working-directory: react_frontend

      - run: npm ci && npm run build
        working-directory: react_frontend
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAR_WIKI_13179 }}"
          projectId: car-wiki-13179
